# Generated by Django 6.0.2 on 2026-02-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceitem",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("New", "New"), ("Used", "Used")],
                max_length=20,
                null=True,
            ),
        ),
    ]
