# Generated by Django 6.0.2 on 2026-02-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_marketplaceitem_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("Offer", "Offer"),
                    ("Wanted", "Wanted"),
                    ("Giveaway", "Giveaway"),
                ],
                max_length=10,
            ),
        ),
    ]
