# Generated by Django 6.0.2 on 2026-02-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_marketplaceitem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceitem",
            name="slug",
            field=models.SlugField(),
        ),
    ]
