# Generated by Django 6.0.2 on 2026-02-15 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="contact_phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)]
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="location",
            field=models.CharField(
                max_length=150,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="title",
            field=models.CharField(
                max_length=120,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
